# Generated by Django 3.2.5 on 2021-08-07 18:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True, auto_now=True)),
                ('nbu_usd', models.FloatField()),
                ('nbu_eur', models.FloatField()),
                ('privat_usd_sale', models.FloatField()),
                ('privat_usd_bay', models.FloatField()),
                ('privat_eur_sale', models.FloatField()),
                ('privat_eur_bay', models.FloatField()),
                ('mono_usd_sale', models.FloatField()),
                ('mono_usd_bay', models.FloatField()),
                ('mono_eur_sale', models.FloatField()),
                ('mono_eur_bay', models.FloatField()),
            ],
            options={
                'verbose_name': 'Курс валют',
                'verbose_name_plural': 'Курсы валют',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='GovBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_currency', models.IntegerField()),
                ('name_currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR')], max_length=3)),
                ('value_currency', models.FloatField()),
                ('date_carrency', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
