# Generated by Django 3.2.6 on 2021-08-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True, auto_now=True)),
                ('nbu_usd', models.FloatField()),
                ('nbu_eur', models.FloatField()),
                ('privat_usd_sale', models.FloatField()),
                ('privat_usd_bay', models.FloatField()),
                ('privat_eur_sale', models.FloatField()),
                ('privat_eur_bay', models.FloatField()),
                ('mono_usd_sale', models.FloatField()),
                ('mono_usd_bay', models.FloatField()),
                ('mono_eur_sale', models.FloatField()),
                ('mono_eur_bay', models.FloatField()),
            ],
            options={
                'verbose_name': 'Курс валют',
                'verbose_name_plural': 'Курсы валют',
                'ordering': ['-date'],
            },
        ),
    ]
