# Generated by Django 3.2.5 on 2021-08-26 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='mono_eur_bay',
            new_name='mono_eur_buy',
        ),
        migrations.RenameField(
            model_name='currency',
            old_name='mono_usd_bay',
            new_name='mono_usd_buy',
        ),
        migrations.RenameField(
            model_name='currency',
            old_name='privat_eur_bay',
            new_name='privat_eur_buy',
        ),
        migrations.RenameField(
            model_name='currency',
            old_name='privat_usd_bay',
            new_name='privat_usd_buy',
        ),
    ]
