# Generated by Django 3.2.5 on 2021-08-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Курс валют'},
        ),
        migrations.AlterField(
            model_name='currency',
            name='date',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
