# Generated by Django 3.2.5 on 2021-08-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_auto_20210806_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='date',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
