# Generated by Django 2.0.5 on 2021-07-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_auto_20210618_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('nbu_usd', models.FloatField()),
                ('nbu_eur', models.FloatField()),
                ('privat_usd_sale', models.FloatField()),
                ('privat_usd_bay', models.FloatField()),
                ('privat_eur_sale', models.FloatField()),
                ('privat_eur_bay', models.FloatField()),
            ],
        ),
    ]
