# Generated by Django 3.2.5 on 2021-10-13 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_alter_currency_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['-date'], 'permissions': [('monobank_currency_view', 'Can see monobanck currency'), ('privatbank_currency_view', 'Can see privatbank currency')], 'verbose_name': 'Курс валют', 'verbose_name_plural': 'Курсы валют'},
        ),
    ]
