# Generated by Django 3.2.5 on 2021-07-06 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['nbu_usd', 'nbu_eur'], 'verbose_name_plural': 'Курс валют'},
        ),
    ]
