# Generated by Django 3.2.5 on 2021-07-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InPlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_inplay', models.IntegerField()),
                ('scorre_home', models.IntegerField()),
                ('scorre_away', models.IntegerField()),
                ('amaunt_match', models.IntegerField()),
                ('runner_home', models.CharField(max_length=50)),
                ('runner_away', models.CharField(max_length=50)),
                ('football_liga', models.CharField(max_length=100)),
                ('url_match', models.CharField(max_length=500)),
            ],
        ),
    ]
